package com.example.arfashion.presentation.services

import okhttp3.Interceptor
import okhttp3.Response

class AuthInterceptor : Interceptor {
    override fun intercept(chain: Interceptor.Chain): Response {
        val requestBuilder = chain.request().newBuilder()
        //todo: get accesstoken from pref here

        //fixme: this is hard code
        val accessToken =
            "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoie1wiX2lkXCI6XCI2MGE5MTg5OTA2MGFlZDAwMTVmYmY1NmZcIixcIm5hbWVcIjpcIlbDtSBUaGFuaCBQaG9uZ1wiLFwiZW1haWxcIjpcInBob25ndnRAYWxpdmUudm5cIixcImF2YXRhclwiOm51bGwsXCJwaG9uZVwiOm51bGwsXCJnZW5kZXJcIjpcIk1hbGVcIixcImJpcnRoZGF5XCI6bnVsbCxcInJlZnJlc2hfdG9rZW5cIjp7XCJ0b2tlblwiOlwiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmtZWFJoSWpvaWUxd2lYMmxrWENJNlhDSTJNR0U1TVRnNU9UQTJNR0ZsWkRBd01UVm1ZbVkxTm1aY0lpeGNJbTVoYldWY0lqcGNJbGJEdFNCVWFHRnVhQ0JRYUc5dVoxd2lMRndpWlcxaGFXeGNJanBjSW5Cb2IyNW5kblJBWVd4cGRtVXVkbTVjSWl4Y0luQm9iMjVsWENJNmJuVnNiQ3hjSW1GMllYUmhjbHdpT201MWJHd3NYQ0puWlc1a1pYSmNJanBjSWsxaGJHVmNJaXhjSW1KcGNuUm9aR0Y1WENJNmJuVnNiQ3hjSW5KbFpuSmxjMmhmZEc5clpXNWNJanA3WENKMGIydGxibHdpT201MWJHd3NYQ0pwWVhSY0lqcHVkV3hzTEZ3aVpYaHdYQ0k2Ym5Wc2JIMHNYQ0poWTJOdmRXNTBYM04wWVhSMWMxd2lPbHdpWW14dlkydGNJaXhjSW1OaGNuUmNJanA3WENKZmFXUmNJanBjSWpZd1lUa3hPRGs1TURZd1lXVmtNREF4TldaaVpqVTJaVndpTEZ3aWRHOTBZV3hjSWpvd2ZTeGNJbVpoZG05MWNtbDBaWE5jSWpwYlhYMGlMQ0pwWVhRaU9qRTJNakUyT1RRM05UUXNJbVY0Y0NJNk1UWXlOREk0TmpjMU5IMC5vUVBjNWFxQUJ1aV9SQVk0dE9VS2tLUWFrVXdDTHV6Z2dBM2h5c3lVN2p3XCIsXCJpYXRcIjpcIjE2MjE2OTQ3NTRcIixcImV4cFwiOlwiMTYyNDI4Njc1NFwifSxcImFjY291bnRfc3RhdHVzXCI6XCJ1bmJsb2NrXCIsXCJjYXJ0XCI6e1wiX2lkXCI6XCI2MGE5MTg5OTA2MGFlZDAwMTVmYmY1NmVcIixcInRvdGFsXCI6MX0sXCJmYXZvdXJpdGVzXCI6W119IiwiaWF0IjoxNjIxNzc2OTE5LCJleHAiOjE2MjQzNjg5MTl9.wr2dlbXfbnOzTbWxyMNhC5TOIYLL9UNO0tEmMgd7wis"
        requestBuilder.addHeader("Authorization", "Bearer $accessToken")

        return chain.proceed(requestBuilder.build())
    }

}